# Generated by Django 4.1 on 2022-09-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_news', models.CharField(max_length=200, verbose_name='Название статьи')),
                ('data', models.DateField(verbose_name='Дата публикации')),
                ('text', models.TextField(verbose_name='Текст статьи')),
                ('image_front', models.ImageField(upload_to='images/')),
                ('image_add1', models.ImageField(blank=True, upload_to='images/')),
                ('image_add2', models.ImageField(blank=True, upload_to='images/')),
                ('image_add3', models.ImageField(blank=True, upload_to='images/')),
                ('image_add4', models.ImageField(blank=True, upload_to='images/')),
                ('image_add5', models.ImageField(blank=True, upload_to='images/')),
                ('author', models.CharField(max_length=100, verbose_name='Автор статьи')),
            ],
            options={
                'verbose_name': 'Актуальные новости',
            },
        ),
    ]
