# Generated by Django 4.1 on 2022-09-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=200, verbose_name='Термин')),
                ('description', models.TextField(verbose_name='Описание значения')),
            ],
            options={
                'verbose_name': 'Термины в Доп. Инфо',
            },
        ),
    ]
