# Generated by Django 4.1 on 2022-09-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('date_of_birth', models.CharField(max_length=20, verbose_name='День Рождения')),
                ('year_of_joining', models.CharField(max_length=20, verbose_name='Количество лет в клубе')),
                ('rank', models.CharField(max_length=20, verbose_name='Клубное Звание')),
                ('status', models.CharField(max_length=20, verbose_name='Статус')),
                ('vk', models.CharField(blank=True, max_length=20, verbose_name='Страница в соц сетях')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Контактный номер телефона')),
                ('image', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Состав клуба',
            },
        ),
    ]
